server:
  port: 8084

spring:
  application:
    name: spring-6-data-rest
  data:
    rest:
      base-path: /api/v4
      
management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always      
      
logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      - path: /actuator/health  
      # this is a workaround to fix logbook bug when log level is set on trace  
      - path: /web/**   
      - path: /webjars/**   
        
security:
  cors:
    allowed-origins:
      - http://localhost:8080 # gateway project runs on port 8080
      - http://127.0.0.1:8080 # gateway project runs on port 8080    
  
  
