server:
  port: 8084

spring:
  application:
    name: spring-6-data-rest
  data:
    rest:
      base-path: /api/v4
      
management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    configprops:
      # WARNING: SECURITY RISK - DO NOT USE IN PRODUCTION ENVIRONMENT
      # This configuration exposes sensitive data and should only be used for development or testing purposes.
      # Ensure this is disabled in any environment where security is a concern.
      show-values: ALWAYS
    env:
      show-values: always
    health:
      probes:
        enabled: true
      show-details: always      
      
logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      # Exclude HTML-related calls and specific endpoints that Logbook doesn't handle correctly
      - path: /actuator/health/**
      - path: /h2-console/**  # Exclude H2 console
      - path: /swagger-ui/**  # Exclude Swagger UI if used
      - path: /v3/api-docs/** # Exclude OpenAPI docs if used
      - path: /favicon.ico
      - path: /web/**
      - path: /webjars/**
        # Add more exclusions as needed
        
security:
  cors:
    allowed-origins:
      - http://localhost:8080 # gateway project runs on port 8080
      - http://127.0.0.1:8080 # gateway project runs on port 8080    
  
  
