### beers
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v4/beers
Accept: application/json
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=spring-6-data-rest

### customers
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v4/customers
Accept: application/json
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=spring-6-data-rest
